spring:
  application:
    name: backend
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url:
    username:
    password:
    driverClassName: org.postgresql.Driver
